id = "kanagawa-theme"
name = "Kanagawa"
version = "0.1.0"
schema_version = 1
authors = ["rebelot", "Chrono"]
description = "Kanagawa colorscheme theme for Zed, inspired by the colors of the famous painting by Katsushika Hokusai"
repository = "https://github.com/rebelot/kanagawa.nvim"
themes = ["themes/kanagawa.json"]
